vehicle_A:
  vehicle : vehicle_A
  process_id : ['proc']
  line_id : ['line']
  setting_stepseq : ['%%']
  prod : Node_vehicle_A
  with_vehicle : ['Vehicle_B']
  node : SS
  version : 10
  system_admin : 우시명
  delay_min : 90
  viewing_period : 35
  QueryTimeSpan : 1
  SplitTimeSpan : 1
  et_log_show : 30 
  loop_time_sleep_time : 1200 
  test_mode : False
  DB_Setting_mode : False
  high_qual_ppt_mode : False
  KNOXID : simyung.woo
  user_name : simyung.woo
  email_receiver : ['POWER_USER']
  YOUR_PROJECT : AAA
  fab_QueryTimeSpan : 50
  inline_QueryTimeSpan : 1
  report_making : True
  ptype_lot_turnoff : False
  specific_dc_layer : False
  ref_turnoff : True
